#%RAML 1.0
title: API Documentation
version: 1.0

# Resource: API Documentation
/doc:
  get:
    description: Retrieve the RAML API documentation
    responses:
      200:
        body:
          application/raml:
            example: |
              #%RAML 1.0
              title: API Documentation
              version: 1.0
              ...

# Resource: Etablissements
/etablissements:
  /infractions:
    description: Retrieve the list of establishments with the number of infractions
    get:
      description: Get the sorted list of establishments with the count of infractions
      responses:
        200:
          body:
            application/json:
              example: |
                [
                  {
                    "etablissement": "Etablissement A",
                    "nombre_infractions": 10
                  },
                  {
                    "etablissement": "Etablissement B",
                    "nombre_infractions": 5
                  }
                ]
